-- Comprehensive gym exercises seed file

INSERT INTO exercises (name, description, tracking_type) VALUES
-- CHEST EXERCISES
('Barbell Bench Press', 'Compound pressing movement targeting chest, shoulders, and triceps. Lie on flat bench and press barbell from chest to full arm extension.', 'reps_sets_weight'),
('Incline Barbell Bench Press', 'Upper chest focused bench press on 30-45 degree incline bench.', 'reps_sets_weight'),
('Decline Barbell Bench Press', 'Lower chest focused bench press on decline bench.', 'reps_sets_weight'),
('Dumbbell Bench Press', 'Chest press with dumbbells allowing greater range of motion than barbell.', 'reps_sets_weight'),
('Incline Dumbbell Bench Press', 'Upper chest focused dumbbell press on incline bench.', 'reps_sets_weight'),
('Decline Dumbbell Bench Press', 'Lower chest focused dumbbell press on decline bench.', 'reps_sets_weight'),
('Dumbbell Flyes', 'Isolation exercise for chest performed with dumbbells in arc motion.', 'reps_sets_weight'),
('Incline Dumbbell Flyes', 'Upper chest isolation with dumbbells on incline bench.', 'reps_sets_weight'),
('Cable Flyes', 'Chest isolation using cable machine with continuous tension throughout movement.', 'reps_sets_weight'),
('Low Cable Flyes', 'Cable flyes from low position targeting upper chest.', 'reps_sets_weight'),
('High Cable Flyes', 'Cable flyes from high position targeting lower chest.', 'reps_sets_weight'),
('Push-Ups', 'Classic bodyweight chest, shoulder, and triceps exercise.', 'reps_sets_weight'),
('Wide Grip Push-Ups', 'Push-up variation with hands wider than shoulders to emphasize chest.', 'reps_sets_weight'),
('Diamond Push-Ups', 'Push-up with hands close together forming diamond shape, emphasizing triceps.', 'reps_sets_weight'),
('Decline Push-Ups', 'Push-ups with feet elevated to increase difficulty and upper chest emphasis.', 'reps_sets_weight'),
('Incline Push-Ups', 'Push-ups with hands elevated for easier variation.', 'reps_sets_weight'),
('Chest Dips', 'Bodyweight exercise on parallel bars with forward lean for chest emphasis.', 'reps_sets_weight'),
('Machine Chest Press', 'Chest press on machine providing guided movement pattern.', 'reps_sets_weight'),
('Incline Machine Press', 'Upper chest focused machine press.', 'reps_sets_weight'),
('Pec Deck Machine', 'Chest isolation machine exercise bringing arms together in front of body.', 'reps_sets_weight'),
('Smith Machine Bench Press', 'Bench press on Smith machine with fixed bar path.', 'reps_sets_weight'),
('Incline Smith Machine Press', 'Incline press variation on Smith machine.', 'reps_sets_weight'),
('Landmine Press', 'Single arm or double arm chest press using barbell in landmine attachment.', 'reps_sets_weight'),
('Single Arm Dumbbell Press', 'Unilateral chest press with one dumbbell.', 'reps_sets_weight'),
('Plate Press', 'Squeezing weight plate while pressing to engage chest.', 'reps_sets_weight'),

-- BACK EXERCISES
('Deadlift', 'Compound movement lifting barbell from floor, engaging entire posterior chain.', 'reps_sets_weight'),
('Romanian Deadlift', 'Hip hinge movement focusing on hamstrings and lower back with slight knee bend.', 'reps_sets_weight'),
('Sumo Deadlift', 'Deadlift with wide stance and hands inside legs.', 'reps_sets_weight'),
('Trap Bar Deadlift', 'Deadlift using hexagonal trap bar allowing more upright posture.', 'reps_sets_weight'),
('Pull-Ups', 'Bodyweight exercise pulling body up to bar with overhand grip.', 'reps_sets_weight'),
('Chin-Ups', 'Pull-up variation with underhand grip emphasizing biceps.', 'reps_sets_weight'),
('Wide Grip Pull-Ups', 'Pull-ups with extra wide grip targeting lats.', 'reps_sets_weight'),
('Neutral Grip Pull-Ups', 'Pull-ups with palms facing each other.', 'reps_sets_weight'),
('Assisted Pull-Ups', 'Pull-ups with assistance from machine or band.', 'reps_sets_weight'),
('Barbell Row', 'Bent over row with barbell targeting middle back.', 'reps_sets_weight'),
('Pendlay Row', 'Strict barbell row with dead stop on floor between reps.', 'reps_sets_weight'),
('T-Bar Row', 'Row using T-bar or landmine with close grip.', 'reps_sets_weight'),
('Dumbbell Row', 'Single arm row with dumbbell, one knee on bench.', 'reps_sets_weight'),
('Two Arm Dumbbell Row', 'Bent over row with both dumbbells simultaneously.', 'reps_sets_weight'),
('Chest Supported Row', 'Row performed lying face down on incline bench.', 'reps_sets_weight'),
('Seated Cable Row', 'Horizontal row on cable machine in seated position.', 'reps_sets_weight'),
('Wide Grip Cable Row', 'Cable row with wide grip bar attachment.', 'reps_sets_weight'),
('Close Grip Cable Row', 'Cable row with close grip attachment.', 'reps_sets_weight'),
('Single Arm Cable Row', 'Unilateral cable row.', 'reps_sets_weight'),
('Lat Pulldown', 'Vertical pulling movement on lat pulldown machine.', 'reps_sets_weight'),
('Wide Grip Lat Pulldown', 'Lat pulldown with wide grip.', 'reps_sets_weight'),
('Close Grip Lat Pulldown', 'Lat pulldown with close grip.', 'reps_sets_weight'),
('Reverse Grip Lat Pulldown', 'Lat pulldown with underhand grip.', 'reps_sets_weight'),
('Single Arm Lat Pulldown', 'Unilateral lat pulldown.', 'reps_sets_weight'),
('Straight Arm Pulldown', 'Lat isolation keeping arms straight throughout movement.', 'reps_sets_weight'),
('Face Pulls', 'Cable exercise pulling rope to face level for rear delts and upper back.', 'reps_sets_weight'),
('Inverted Row', 'Bodyweight row hanging under bar at waist height.', 'reps_sets_weight'),
('Seal Row', 'Row performed lying face down on elevated bench.', 'reps_sets_weight'),
('Meadows Row', 'Single arm row using barbell in landmine setup.', 'reps_sets_weight'),
('Rack Pulls', 'Partial deadlift starting from rack at knee height.', 'reps_sets_weight'),
('Good Mornings', 'Hip hinge movement with barbell on back shoulders.', 'reps_sets_weight'),
('Hyperextensions', 'Lower back exercise on hyperextension bench.', 'reps_sets_weight'),
('Back Extensions', 'Similar to hyperextensions, focusing on spinal erectors.', 'reps_sets_weight'),
('Reverse Hyperextensions', 'Hyperextension variation lifting legs instead of torso.', 'reps_sets_weight'),
('Superman', 'Bodyweight lower back exercise lying prone and lifting limbs.', 'time_based'),
('Machine Row', 'Back row performed on machine.', 'reps_sets_weight'),
('Yates Row', 'Underhand barbell row with more upright torso angle.', 'reps_sets_weight'),

-- SHOULDER EXERCISES
('Overhead Press', 'Standing barbell press from shoulders to overhead.', 'reps_sets_weight'),
('Military Press', 'Strict overhead press with feet together.', 'reps_sets_weight'),
('Push Press', 'Overhead press with leg drive assistance.', 'reps_sets_weight'),
('Seated Overhead Press', 'Barbell press performed seated.', 'reps_sets_weight'),
('Dumbbell Shoulder Press', 'Overhead press with dumbbells.', 'reps_sets_weight'),
('Seated Dumbbell Press', 'Dumbbell press performed seated.', 'reps_sets_weight'),
('Arnold Press', 'Dumbbell press with rotation from front to sides.', 'reps_sets_weight'),
('Single Arm Dumbbell Press', 'Unilateral overhead press.', 'reps_sets_weight'),
('Lateral Raises', 'Side delt isolation lifting dumbbells to sides.', 'reps_sets_weight'),
('Cable Lateral Raises', 'Lateral raises using cable machine.', 'reps_sets_weight'),
('Front Raises', 'Front delt isolation lifting weight to front.', 'reps_sets_weight'),
('Cable Front Raises', 'Front raises using cable.', 'reps_sets_weight'),
('Rear Delt Flyes', 'Rear delt isolation with dumbbells bent over.', 'reps_sets_weight'),
('Cable Rear Delt Flyes', 'Rear delt flyes using cables.', 'reps_sets_weight'),
('Reverse Pec Deck', 'Rear delt isolation on pec deck machine facing backward.', 'reps_sets_weight'),
('Upright Row', 'Pulling bar or dumbbells up along torso to chin level.', 'reps_sets_weight'),
('High Pull', 'Explosive upright row variation.', 'reps_sets_weight'),
('Barbell Shrugs', 'Trap exercise shrugging shoulders with barbell.', 'reps_sets_weight'),
('Dumbbell Shrugs', 'Shrugs performed with dumbbells.', 'reps_sets_weight'),
('Behind the Neck Press', 'Overhead press lowering bar behind neck.', 'reps_sets_weight'),
('Machine Shoulder Press', 'Shoulder press on machine.', 'reps_sets_weight'),
('Smith Machine Shoulder Press', 'Shoulder press on Smith machine.', 'reps_sets_weight'),
('Pike Push-Ups', 'Push-up variation in pike position emphasizing shoulders.', 'reps_sets_weight'),
('Handstand Push-Ups', 'Advanced shoulder exercise doing push-ups in handstand.', 'reps_sets_weight'),
('Landmine Press', 'Single arm overhead press using landmine setup.', 'reps_sets_weight'),
('Cuban Press', 'Combination exercise for shoulder health and strength.', 'reps_sets_weight'),
('Lu Raises', 'Y-raises for shoulders lying on incline bench.', 'reps_sets_weight'),
('Bent Over Lateral Raises', 'Lateral raises performed bent over for rear delts.', 'reps_sets_weight'),

-- LEG EXERCISES
('Back Squat', 'Compound leg exercise with barbell on back shoulders.', 'reps_sets_weight'),
('Front Squat', 'Squat with barbell held in front on front shoulders.', 'reps_sets_weight'),
('High Bar Squat', 'Back squat with bar higher on traps.', 'reps_sets_weight'),
('Low Bar Squat', 'Back squat with bar lower on rear delts.', 'reps_sets_weight'),
('Box Squat', 'Squat sitting back to box before standing.', 'reps_sets_weight'),
('Pause Squat', 'Squat with pause at bottom position.', 'reps_sets_weight'),
('Goblet Squat', 'Squat holding dumbbell or kettlebell at chest.', 'reps_sets_weight'),
('Bulgarian Split Squat', 'Single leg squat with rear foot elevated.', 'reps_sets_weight'),
('Split Squat', 'Stationary lunge position squat.', 'reps_sets_weight'),
('Walking Lunges', 'Lunges moving forward with each rep.', 'reps_sets_weight'),
('Reverse Lunges', 'Lunges stepping backward.', 'reps_sets_weight'),
('Forward Lunges', 'Lunges stepping forward.', 'reps_sets_weight'),
('Lateral Lunges', 'Lunges stepping to the side.', 'reps_sets_weight'),
('Curtsy Lunges', 'Lunge with rear leg crossing behind.', 'reps_sets_weight'),
('Leg Press', 'Compound leg exercise on leg press machine.', 'reps_sets_weight'),
('Hack Squat', 'Squat performed on hack squat machine.', 'reps_sets_weight'),
('Smith Machine Squat', 'Squat on Smith machine with fixed bar path.', 'reps_sets_weight'),
('Leg Extension', 'Quad isolation on leg extension machine.', 'reps_sets_weight'),
('Leg Curl', 'Hamstring isolation on leg curl machine.', 'reps_sets_weight'),
('Seated Leg Curl', 'Leg curl performed in seated position.', 'reps_sets_weight'),
('Lying Leg Curl', 'Leg curl lying face down.', 'reps_sets_weight'),
('Standing Leg Curl', 'Single leg curl standing at machine.', 'reps_sets_weight'),
('Nordic Hamstring Curl', 'Advanced bodyweight hamstring exercise.', 'reps_sets_weight'),
('Calf Raises', 'Calf exercise raising up on toes.', 'reps_sets_weight'),
('Standing Calf Raises', 'Calf raises performed standing.', 'reps_sets_weight'),
('Seated Calf Raises', 'Calf raises performed seated.', 'reps_sets_weight'),
('Single Leg Calf Raises', 'Unilateral calf raises.', 'reps_sets_weight'),
('Donkey Calf Raises', 'Calf raises bent over with weight on lower back.', 'reps_sets_weight'),
('Leg Press Calf Raises', 'Calf raises performed on leg press machine.', 'reps_sets_weight'),
('Step-Ups', 'Stepping up onto elevated platform alternating legs.', 'reps_sets_weight'),
('Box Jumps', 'Explosive jump onto elevated box.', 'reps_sets_weight'),
('Jump Squats', 'Explosive squat with jump at top.', 'reps_sets_weight'),
('Pistol Squats', 'Single leg squat with other leg extended forward.', 'reps_sets_weight'),
('Sissy Squats', 'Quad focused squat leaning back.', 'reps_sets_weight'),
('Wall Sits', 'Isometric hold in squat position against wall.', 'time_based'),
('Sumo Squat', 'Squat with wide stance and toes pointed out.', 'reps_sets_weight'),
('Single Leg Press', 'Leg press with one leg at a time.', 'reps_sets_weight'),
('Glute Bridge', 'Hip thrust lying on back driving through heels.', 'reps_sets_weight'),
('Hip Thrust', 'Glute exercise with shoulders elevated on bench.', 'reps_sets_weight'),
('Barbell Hip Thrust', 'Hip thrust with barbell across hips.', 'reps_sets_weight'),
('Single Leg Hip Thrust', 'Unilateral hip thrust.', 'reps_sets_weight'),
('Cable Pull Through', 'Hip hinge movement using cable between legs.', 'reps_sets_weight'),
('Glute Kickbacks', 'Glute isolation kicking leg back.', 'reps_sets_weight'),
('Cable Glute Kickbacks', 'Glute kickbacks using cable machine.', 'reps_sets_weight'),
('Fire Hydrants', 'Hip abduction on hands and knees.', 'reps_sets_weight'),
('Clamshells', 'Hip abduction lying on side.', 'reps_sets_weight'),
('Hip Abduction Machine', 'Hip abduction on machine.', 'reps_sets_weight'),
('Hip Adduction Machine', 'Hip adduction on machine.', 'reps_sets_weight'),
('Goblet Squat Pulses', 'Small pulsing reps at bottom of goblet squat.', 'reps_sets_weight'),
('Frog Pumps', 'Hip thrust variation with soles of feet together.', 'reps_sets_weight'),

-- ARM EXERCISES (BICEPS)
('Barbell Curl', 'Standing bicep curl with barbell.', 'reps_sets_weight'),
('EZ Bar Curl', 'Bicep curl with EZ curl bar for wrist comfort.', 'reps_sets_weight'),
('Dumbbell Curl', 'Bicep curl with dumbbells.', 'reps_sets_weight'),
('Alternating Dumbbell Curl', 'Curling dumbbells one arm at a time.', 'reps_sets_weight'),
('Hammer Curl', 'Neutral grip curl emphasizing brachialis.', 'reps_sets_weight'),
('Cross Body Hammer Curl', 'Hammer curl across body to opposite shoulder.', 'reps_sets_weight'),
('Concentration Curl', 'Isolated bicep curl seated with elbow on inner thigh.', 'reps_sets_weight'),
('Preacher Curl', 'Bicep curl with upper arms on preacher bench.', 'reps_sets_weight'),
('EZ Bar Preacher Curl', 'Preacher curl using EZ bar.', 'reps_sets_weight'),
('Dumbbell Preacher Curl', 'Preacher curl with dumbbells.', 'reps_sets_weight'),
('Cable Curl', 'Bicep curl using cable machine.', 'reps_sets_weight'),
('High Cable Curl', 'Cable curl with cables at high position.', 'reps_sets_weight'),
('Single Arm Cable Curl', 'Unilateral cable curl.', 'reps_sets_weight'),
('Incline Dumbbell Curl', 'Bicep curl on incline bench for stretch.', 'reps_sets_weight'),
('Spider Curl', 'Curl with chest against steep incline bench.', 'reps_sets_weight'),
('Drag Curl', 'Barbell curl dragging bar up torso.', 'reps_sets_weight'),
('Zottman Curl', 'Curl with rotation from supinated to pronated grip.', 'reps_sets_weight'),
('Reverse Curl', 'Curl with overhand grip.', 'reps_sets_weight'),
('21s', 'Bicep exercise with 7 reps in three ranges of motion.', 'reps_sets_weight'),
('Chin-Up', 'Pull-up with underhand grip emphasizing biceps.', 'reps_sets_weight'),

-- ARM EXERCISES (TRICEPS)
('Close Grip Bench Press', 'Bench press with narrow grip emphasizing triceps.', 'reps_sets_weight'),
('Tricep Dips', 'Dips on parallel bars with upright torso.', 'reps_sets_weight'),
('Bench Dips', 'Dips between two benches.', 'reps_sets_weight'),
('Overhead Tricep Extension', 'Tricep extension with weight overhead.', 'reps_sets_weight'),
('Dumbbell Overhead Extension', 'Overhead extension with dumbbell.', 'reps_sets_weight'),
('EZ Bar Overhead Extension', 'Overhead extension with EZ bar.', 'reps_sets_weight'),
('Single Arm Overhead Extension', 'Unilateral overhead tricep extension.', 'reps_sets_weight'),
('Skull Crushers', 'Lying tricep extension lowering weight to forehead.', 'reps_sets_weight'),
('EZ Bar Skull Crushers', 'Skull crushers with EZ bar.', 'reps_sets_weight'),
('Dumbbell Skull Crushers', 'Skull crushers with dumbbells.', 'reps_sets_weight'),
('Cable Tricep Pushdown', 'Tricep extension pushing cable attachment down.', 'reps_sets_weight'),
('Rope Tricep Pushdown', 'Pushdown using rope attachment.', 'reps_sets_weight'),
('V-Bar Pushdown', 'Pushdown using V-bar attachment.', 'reps_sets_weight'),
('Single Arm Cable Pushdown', 'Unilateral cable pushdown.', 'reps_sets_weight'),
('Reverse Grip Pushdown', 'Pushdown with underhand grip.', 'reps_sets_weight'),
('Overhead Cable Extension', 'Cable extension with cable behind head.', 'reps_sets_weight'),
('Tricep Kickbacks', 'Bent over tricep extension kicking weight back.', 'reps_sets_weight'),
('Cable Kickbacks', 'Kickbacks using cable machine.', 'reps_sets_weight'),
('Diamond Push-Ups', 'Push-ups with hands together emphasizing triceps.', 'reps_sets_weight'),
('Close Grip Push-Ups', 'Push-ups with narrow hand placement.', 'reps_sets_weight'),
('Tate Press', 'Dumbbell press bringing elbows in toward torso.', 'reps_sets_weight'),
('JM Press', 'Hybrid between close grip bench and skull crusher.', 'reps_sets_weight'),

-- FOREARM EXERCISES
('Wrist Curl', 'Forearm curl with palms up.', 'reps_sets_weight'),
('Reverse Wrist Curl', 'Forearm extension with palms down.', 'reps_sets_weight'),
('Behind the Back Wrist Curl', 'Wrist curl with barbell behind back.', 'reps_sets_weight'),
('Farmers Walk', 'Walking while holding heavy weights at sides.', 'distance_based'),
('Plate Pinch', 'Holding weight plates between fingers and thumb.', 'time_based'),
('Dead Hang', 'Hanging from pull-up bar for time.', 'time_based'),
('Wrist Roller', 'Rolling weight up and down on string attached to stick.', 'reps_sets_weight'),
('Reverse Barbell Curl', 'Curl with overhand grip for forearms.', 'reps_sets_weight'),
('Hammer Curl', 'Neutral grip curl working brachioradialis.', 'reps_sets_weight'),

-- CORE/ABS EXERCISES
('Plank', 'Isometric core hold in push-up position.', 'time_based'),
('Side Plank', 'Plank on one forearm facing sideways.', 'time_based'),
('Hollow Body Hold', 'Core hold lying on back with arms and legs extended.', 'time_based'),
('Dead Bug', 'Core exercise alternating opposite arm and leg.', 'reps_sets_weight'),
('Bird Dog', 'Core exercise on hands and knees extending opposite limbs.', 'reps_sets_weight'),
('Crunch', 'Basic abdominal crunch.', 'reps_sets_weight'),
('Bicycle Crunch', 'Alternating knee to elbow crunch.', 'reps_sets_weight'),
('Reverse Crunch', 'Bringing knees toward chest.', 'reps_sets_weight'),
('Sit-Up', 'Full range of motion abdominal exercise.', 'reps_sets_weight'),
('V-Up', 'Bringing hands to feet simultaneously.', 'reps_sets_weight'),
('Toe Touch', 'Reaching hands to feet in crunch motion.', 'reps_sets_weight'),
('Russian Twist', 'Seated rotation exercise for obliques.', 'reps_sets_weight'),
('Leg Raise', 'Raising legs while hanging or lying down.', 'reps_sets_weight'),
('Hanging Leg Raise', 'Leg raises hanging from pull-up bar.', 'reps_sets_weight'),
('Hanging Knee Raise', 'Bringing knees to chest while hanging.', 'reps_sets_weight'),
('Captain''s Chair Leg Raise', 'Leg raise on captain''s chair apparatus.', 'reps_sets_weight'),
('Dragon Flag', 'Advanced core exercise keeping body rigid.', 'reps_sets_weight'),
('Ab Wheel Rollout', 'Rolling ab wheel forward and back.', 'reps_sets_weight'),
('Pallof Press', 'Anti-rotation exercise with cable or band.', 'reps_sets_weight'),
('Cable Crunch', 'Crunch using rope attachment on cable.', 'reps_sets_weight'),
('Rope Crunch', 'Kneeling cable crunch with rope.', 'reps_sets_weight'),
('Machine Crunch', 'Abdominal crunch on machine.', 'reps_sets_weight'),
('Decline Sit-Up', 'Sit-up on decline bench.', 'reps_sets_weight'),
('Weighted Sit-Up', 'Sit-up holding weight plate or dumbbell.', 'reps_sets_weight'),
('Wood Chopper', 'Diagonal cable chop for obliques.', 'reps_sets_weight'),
('Cable Wood Chopper', 'Wood chopping motion using cable.', 'reps_sets_weight'),
('Oblique Crunch', 'Side crunch targeting obliques.', 'reps_sets_weight'),
('Side Bend', 'Standing side flexion with dumbbell.', 'reps_sets_weight'),
('Dumbbell Side Bend', 'Side bend holding dumbbell.', 'reps_sets_weight'),
('Cable Side Bend', 'Side bend using cable.', 'reps_sets_weight'),
('Windshield Wiper', 'Rotating legs side to side hanging or lying.', 'reps_sets_weight'),
('L-Sit', 'Holding body in L position.', 'time_based'),
('Mountain Climbers', 'Dynamic plank bringing knees to chest.', 'reps_sets_weight'),
('Flutter Kicks', 'Small alternating leg kicks lying on back.', 'reps_sets_weight'),
('Scissors', 'Crossing legs over each other lying on back.', 'reps_sets_weight'),
('Heel Touches', 'Alternating touching heels in crunch position.', 'reps_sets_weight'),
('Starfish Crunch', 'Bringing opposite hand to opposite foot in X position.', 'reps_sets_weight'),

-- OLYMPIC LIFTS
('Clean', 'Explosive lift bringing barbell from floor to shoulders.', 'reps_sets_weight'),
('Power Clean', 'Clean catching in partial squat.', 'reps_sets_weight'),
('Hang Clean', 'Clean starting from hang position above knees.', 'reps_sets_weight'),
('Hang Power Clean', 'Power clean from hang position.', 'reps_sets_weight'),
('Snatch', 'Single motion lift from floor to overhead.', 'reps_sets_weight'),
('Power Snatch', 'Snatch catching in partial squat.', 'reps_sets_weight'),
('Hang Snatch', 'Snatch from hang position.', 'reps_sets_weight'),
('Hang Power Snatch', 'Power snatch from hang.', 'reps_sets_weight'),
('Clean and Jerk', 'Clean followed by overhead jerk.', 'reps_sets_weight'),
('Push Jerk', 'Overhead jerk with slight knee bend.', 'reps_sets_weight'),
('Split Jerk', 'Jerk catching in split stance.', 'reps_sets_weight'),
('Clean Pull', 'Pulling portion of clean without catching.', 'reps_sets_weight'),
('Snatch Pull', 'Pulling portion of snatch without catching.', 'reps_sets_weight'),
('Muscle Snatch', 'Snatch without dropping under bar.', 'reps_sets_weight'),
('Muscle Clean', 'Clean without dropping under bar.', 'reps_sets_weight'),

-- FUNCTIONAL/FULL BODY
('Burpee', 'Full body exercise combining squat, plank, and jump.', 'reps_sets_weight'),
('Thruster', 'Front squat to overhead press combination.', 'reps_sets_weight'),
('Wall Ball', 'Squat and throw medicine ball to wall target.', 'reps_sets_weight'),
('Kettlebell Swing', 'Hip hinge movement swinging kettlebell.', 'reps_sets_weight'),
('American Kettlebell Swing', 'Kettlebell swing to overhead position.', 'reps_sets_weight'),
('Russian Kettlebell Swing', 'Kettlebell swing to chest height.', 'reps_sets_weight'),
('Turkish Get-Up', 'Complex movement from lying to standing with weight overhead.', 'reps_sets_weight'),
('Farmers Carry', 'Walking with heavy weights in each hand.', 'distance_based'),
('Suitcase Carry', 'Single arm farmers carry.', 'distance_based'),
('Overhead Carry', 'Walking with weight held overhead.', 'distance_based'),
('Waiter Carry', 'Single arm overhead carry.', 'distance_based'),
('Zercher Carry', 'Walking with barbell in crook of elbows.', 'distance_based'),
('Tire Flip', 'Flipping large tire end over end.', 'reps_sets_weight'),
('Sled Push', 'Pushing weighted sled forward.', 'distance_based'),
('Sled Pull', 'Pulling weighted sled backward or forward.', 'distance_based'),
('Battle Ropes', 'Creating waves with heavy ropes.', 'time_based'),
('Slam Ball', 'Slamming weighted ball to ground.', 'reps_sets_weight'),
('Box Jump', 'Jumping onto elevated box.', 'reps_sets_weight'),
('Broad Jump', 'Horizontal jump for distance.', 'reps_sets_weight'),
('Man Maker', 'Complex exercise combining multiple movements.', 'reps_sets_weight'),
('Devil Press', 'Burpee with dumbbells and overhead press.', 'reps_sets_weight'),
('Dumbbell Complex', 'Series of movements without putting weight down.', 'reps_sets_weight'),
('Barbell Complex', 'Series of barbell movements in sequence.', 'reps_sets_weight'),

-- CARDIO EQUIPMENT
('Treadmill Running', 'Running on treadmill.', 'time_based'),
('Treadmill Walking', 'Walking on treadmill.', 'time_based'),
('Incline Treadmill Walking', 'Walking on inclined treadmill.', 'time_based'),
('Treadmill Sprints', 'High intensity sprint intervals on treadmill.', 'time_based'),
('Rowing Machine', 'Full body cardio on rowing ergometer.', 'time_based'),
('Assault Bike', 'High intensity bike with arm and leg action.', 'time_based'),
('Stationary Bike', 'Cycling on stationary bike.', 'time_based'),
('Spin Bike', 'High intensity cycling on spin bike.', 'time_based'),
('Elliptical', 'Low impact cardio on elliptical machine.', 'time_based'),
('StairMaster', 'Climbing stairs on StairMaster machine.', 'time_based'),
('Stair Climber', 'Continuous stair climbing cardio.', 'time_based'),
('Jacob''s Ladder', 'Climbing on ladder-like cardio machine.', 'time_based'),
('VersaClimber', 'Vertical climbing cardio machine.', 'time_based'),
('SkiErg', 'Simulated cross-country skiing motion.', 'time_based'),

-- PLYOMETRIC/EXPLOSIVE
('Box Jump', 'Explosive jump onto box platform.', 'reps_sets_weight'),
('Depth Jump', 'Dropping from box and immediately jumping.', 'reps_sets_weight'),
('Broad Jump', 'Standing long jump.', 'reps_sets_weight'),
('Vertical Jump', 'Maximum height jump.', 'reps_sets_weight'),
('Jump Squat', 'Squat with explosive jump.', 'reps_sets_weight'),
('Jump Lunge', 'Alternating lunge with jump between.', 'reps_sets_weight'),
('Tuck Jump', 'Jump bringing knees to chest.', 'reps_sets_weight'),
('Plyo Push-Up', 'Explosive push-up leaving ground.', 'reps_sets_weight'),
('Medicine Ball Slam', 'Slamming medicine ball to ground.', 'reps_sets_weight'),
('Medicine Ball Chest Pass', 'Explosive chest pass with medicine ball.', 'reps_sets_weight'),
('Medicine Ball Overhead Throw', 'Throwing medicine ball overhead.', 'reps_sets_weight'),
('Lateral Bound', 'Side to side explosive jump.', 'reps_sets_weight'),
('Single Leg Box Jump', 'Box jump on one leg.', 'reps_sets_weight'),
('Hurdle Hop', 'Hopping over hurdles.', 'reps_sets_weight'),

-- STRETCHING/MOBILITY
('Child''s Pose', 'Resting stretch for back and shoulders.', 'time_based'),
('Cat-Cow Stretch', 'Spinal mobility alternating flexion and extension.', 'reps_sets_weight'),
('Cobra Stretch', 'Back extension stretch lying prone.', 'time_based'),
('Pigeon Pose', 'Hip and glute stretch.', 'time_based'),
('Figure 4 Stretch', 'Hip external rotation stretch.', 'time_based'),
('Hip Flexor Stretch', 'Kneeling hip flexor stretch.', 'time_based'),
('Hamstring Stretch', 'Forward fold stretching hamstrings.', 'time_based'),
('Quad Stretch', 'Standing quad stretch.', 'time_based'),
('Calf Stretch', 'Wall calf stretch.', 'time_based'),
('Shoulder Dislocations', 'Shoulder mobility with band or PVC.', 'reps_sets_weight'),
('Band Pull-Aparts', 'Shoulder health exercise pulling band apart.', 'reps_sets_weight'),
('Foam Rolling', 'Self-myofascial release using foam roller.', 'time_based'),

-- SPECIALIZED/STRONGMAN
('Yoke Walk', 'Walking with weighted yoke across shoulders.', 'distance_based'),
('Atlas Stone Lift', 'Lifting atlas stone from ground to platform.', 'reps_sets_weight'),
('Stone to Shoulder', 'Lifting atlas stone to shoulder.', 'reps_sets_weight'),
('Log Press', 'Overhead press using strongman log.', 'reps_sets_weight'),
('Axle Press', 'Overhead press with thick axle bar.', 'reps_sets_weight'),
('Circus Dumbbell Press', 'Single arm overhead press with large dumbbell.', 'reps_sets_weight'),
('Farmers Frame Carry', 'Carrying loaded frame for distance.', 'distance_based'),
('Husafell Carry', 'Carrying Husafell stone or equivalent load.', 'distance_based'),
('Sandbag Carry', 'Carrying heavy sandbag for distance.', 'distance_based'),
('Sandbag Clean', 'Cleaning sandbag to shoulder or chest.', 'reps_sets_weight'),
('Sandbag Load', 'Loading sandbag onto platform.', 'reps_sets_weight'),
('Tire Flip', 'Flipping large tire end over end.', 'reps_sets_weight'),
('Keg Carry', 'Carrying keg for distance.', 'distance_based'),
('Keg Clean and Press', 'Cleaning keg and pressing overhead.', 'reps_sets_weight'),
('Chain Drag', 'Dragging heavy chains across floor.', 'distance_based'),
('Sled Push', 'Pushing weighted sled forward.', 'distance_based'),
('Sled Pull', 'Pulling weighted sled with harness or rope.', 'distance_based');
